Qa/null version updates
singer-io/tap-mssql pull request #72
Opened 2022-05-26 21:47 UTC by bhtowles

# Description of change
Add test coverage for (https://jira.talendforge.org/browse/TDL-11340) and did some minor updates around those changes in base.py and the logical decimal test case.

# QA steps
 - [ ] automated tests passing
 
# Risks

# Rollback steps
 - revert this branch

2022-06-06 14:30 UTC, kspeer825 requested changes

2022-06-06 14:30 UTC, kspeer825 commented on tests/test_sync_logical_current_log_version_null.py
> +    def setUpClass(cls) -> None:
It seems like we are repeating coverage from the decimal test unnecessarily. I think it would be easier to read if these were more basic records, and the setup was minimized. I don't think looing at json schema and singer metadata is needed to cover the bookmarking test case.

2022-06-06 14:30 UTC, kspeer825 commented on tests/test_sync_logical_current_log_version_null.py
> +        query_list.extend(enable_database_tracking(database_name)) # comment out for null from db case
Does the comment mean this line should not be ran?

2022-06-06 14:30 UTC, kspeer825 commented on tests/test_sync_logical_current_log_version_null.py
> +                                       primary_key=primary_key, tracking=True)) #tracking=False (null from db case)
These inserts are using tracking, but the comments say not to.

2022-06-06 14:30 UTC, kspeer825 commented on tests/test_sync_logical_current_log_version_null.py
> +                if stream == 'data_types_database_dbo_decimal_precisions':
Is it possible to move this outside of the subTest loop, or is there a reason it should be here?

2022-06-06 20:12 UTC, bhtowles commented on tests/test_sync_logical_decimal.py
> +        # self.assertEqual(record_count_by_stream, expected_count) # TODO update expected_count so this passes?
Removed

2022-06-06 20:20 UTC, bhtowles commented on tests/test_sync_logical_current_log_version_null.py
> +                                       primary_key=primary_key, tracking=True)) #tracking=False (null from db case)
Cleaned up comments.

2022-06-06 20:40 UTC, bhtowles commented on tests/test_sync_logical_current_log_version_null.py
> +                if stream == 'data_types_database_dbo_decimal_precisions':
I presume it is possible.  It was placed here for convenience since state and bookmark were already defined for this scope.  If there is something to be gained I can bump it out a level and set state and bookmark separately for this set of assertions.

2022-06-06 20:41 UTC, bhtowles commented on tests/test_sync_logical_min_valid_version_null.py
> +        self.assertIn('Change Tracking is not enabled',exit_status['tap_error_message'])
Thanks

2022-06-06 20:44 UTC, bhtowles commented on tests/test_sync_logical_current_log_version_null.py
> +    def setUpClass(cls) -> None:
Let's discuss.  I agree there is a lot of duplicate coverage but I wasn't sure how much could be removed and how to remove it without impacting the test.  It was also nice to have a static set up that we know works in one test as a baseline but this is not necessary at this point.

2022-06-15 14:11 UTC, kspeer825 approved these changes
Appproved with 1 minor comment

2022-06-15 14:11 UTC, kspeer825 commented on tests/test_sync_logical_decimal.py
> +                # TODO the 2 tables replicate differently https://jira.talendforge.org/browse/TDL-19406
Is this a bug? If so can you mark it with BUG

2022-06-15 15:29 UTC, merged