Qa/table reset
singer-io/tap-mssql pull request #74
Opened 2022-06-14 00:10 UTC by bhtowles

# Description of change
Implement table reset tests for incremental and log based replication.

# QA steps
 - [ ] automated tests passing
 - [ ] manual qa steps passing (list below)
 
# Risks

# Rollback steps
 - revert this branch

2022-06-15 20:40 UTC, kspeer825 requested changes

2022-06-15 20:40 UTC, kspeer825 commented on tests/test_table_reset_incremental.py
> +        reset_stream = stream # order is random
I don't think this should be random, we should hardcode which stream to reset.

2022-06-15 20:40 UTC, kspeer825 commented on tests/test_table_reset_incremental.py
> +                #print(f'Table version: {table_version[stream]}, new_table_version: {new_table_version}')
can be removed

2022-06-15 20:40 UTC, kspeer825 commented on tests/test_table_reset_incremental.py
> +                                                 expected_row, actual_row))
```suggestion
                        self.assertDictEqual(expected_row["data"],  actual_row["data"])

```

2022-06-15 20:40 UTC, kspeer825 commented on tests/test_table_reset_logical.py
> +        for stream in self.expected_streams():
I don't think checking all these assertions for the first sync are necessary since they are covered in other tests.

2022-06-15 20:40 UTC, kspeer825 commented on tests/test_table_reset_logical.py
> +        # invoke the sync job AGAIN after resetting log version and verify expected records
There are a lot of assertions in this section. I think the important thing to verify is that the tap does the full table historical sync again. I think that can be boiled down to checking 
- the same records for the initial sync are replicated (could just check the primary keys, or could compare the whole records)
- the activate version messages come through (2 of them)
- the table version increments form the initial sync.

2022-06-15 20:40 UTC, kspeer825 commented on tests/test_table_reset_logical.py
> +        # ------------------------------------------------------------------------------------------
Isn't this case covered elsewhere in the suite?

2022-06-15 22:33 UTC, bhtowles commented on tests/test_table_reset_incremental.py
> +                #print(f'Table version: {table_version[stream]}, new_table_version: {new_table_version}')
Removed.

2022-06-15 22:36 UTC, bhtowles commented on tests/test_table_reset_logical.py
> +        for stream in self.expected_streams():
refactored based on new behavior after setting state to mimic the app.  I like having a bench mark before and after check as it's only a 75 second test or so.

2022-06-15 22:37 UTC, bhtowles commented on tests/test_table_reset_logical.py
> +        # invoke the sync job AGAIN after resetting log version and verify expected records
After the refactor we call the same function to run all the same assertions again.  May be a bit overkill but low cost and maintainable.

2022-06-15 22:44 UTC, bhtowles commented on tests/test_table_reset_incremental.py
> +        reset_stream = stream # order is random
It wasn't my initial intent to make it random as I didn't realize the order of the streams weren't fixed as they are in some other taps.  But after recognizing this, it seemed better to test both streams than to hardcode one.  Since there are only two streams in this test I'm not sold that it's worth effort to revert and only test one.  Is there a complexity, maintainability, or other factor that discourages this type of pattern?

2022-06-15 22:57 UTC, bhtowles commented on tests/test_table_reset_incremental.py
> +                                                 expected_row, actual_row))
Updated

2022-06-15 23:06 UTC, bhtowles commented on tests/test_table_reset_logical.py
> +        # ------------------------------------------------------------------------------------------
Not exactly.  It appears all the other successful sync logical tests have more complex inserts, updates, and deletes between syncs.

2022-06-17 14:15 UTC, kspeer825 requested changes

2022-06-17 20:21 UTC, bhtowles commented on tests/test_table_reset_incremental.py
> +        reset_stream = stream # order is random
Hard coded for one stream reset.

2022-06-17 20:25 UTC, bhtowles commented on tests/test_table_reset_logical.py
> +        for stream in self.expected_streams():
Removed assertions for first sync to prevent duplicate failures.

2022-06-21 14:03 UTC, kspeer825 approved these changes

2022-06-21 14:07 UTC, merged